const CODORNA = (prefix, sender) => {
	return `KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK
	CODORNA CREW(OOFF&HDBR)
	CODORNA TEM 80% DE SER GAY LKKKKK MAS DE BOAS 
    CLIKE PARA VER O CODORNA[https://images.app.goo.gl/DLvz2psWVdLezPFT6]
	ESSE EO CODORNA

`
}

exports.CODORNA = CODORNA
