const DOMINAT = (prefix, sender) => {
	return `HHHHHHHHH DOMINAT 
	CREW(OOFF&HSBR)
	DOMINAT E DOIDO KKKKK MAS E GENTE BOA DOMINA TEM 
	10% DE SER GAY ELE FEZ O TESTE MAS DEU 10% ENTAO ESTA LIVE
`
}

exports.DOMINAT = DOMINAT
