const FELESPA = (prefix, sender) => {
	return `FELESPINHA E GORDINHO 
	GOSTA DE SALADA LLLL CREW(OOF&$HCBR)
	ELE FEZ O TESTE TMB DEU 100% DE SER GAYYY
	KKKK
	ELE SABE FAZER SRIPT,UPDATE,SPRX 
	
`
}

exports.FELESPA = FELESPA
