const OOFF = (prefix, sender) => {
	return `OOFF MANDA OOFF 
	SE TU E MEMBRO COMUM DEVE UM PIZZA PRA NOIA  HEIN KKKKKK
	SEJA VEM VINDO AO MENU DO OOFF, O BOT ESTA PARA AJUDAR OK?
	VAMOS LA PARA CADA COMANDO DIGIDE (!)
	-----------------------------------
	!STICKER
	!TOIM
	!TTS
	!FELESPA
	!TERRA
	!PIVETINHO
	!DOMINAT
	!MALOKA
	!CODORNA
    !PEDRO
    !PANTERA
	!KABULOSO
`
}

exports.OOFF = OOFF